#!/usr/bin/env node

/**
 * Download latest release of Move Language Server for user's OS
 * @module move-ls-loader
 */

'use strict';

const fs    = require('fs');
const path  = require('path');
const https = require('https');
const conf  = require('package.json')['move-ls'];

// possible versions for
const LINUX  = 'linux';
const DARWIN = 'darwin';
const WIN32  = 'win32.exe';

const OS     = {darwin: DARWIN, linux: LINUX, win32: WIN32}[process.platform];
const URL    = `https://github.com/${conf.repository}/releases/download/${conf.version}/move-language-server-${OS}`;
const target = (OS === WIN32) ? 'bin/move-ls.exe' : 'bin/move-ls';

https.get(URL, (res) => {
    https.get(res.headers.location, (res) => {
        res.pipe(fs.createWriteStream(path.resolve(target), {mode: "755"}));
    });
});
