on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        - uses: actions/checkout@v2
        - run: git fetch --depth=1 origin +refs/tags/${{ steps.get_version.outputs.VERSION }}:refs/tags/${{ steps.get_version.outputs.VERSION }}
        - run: git for-each-ref --format="## %(subject) %0a%0a %(body)" refs/tags/${{ steps.get_version.outputs.VERSION }} > body.md
        - uses: ncipollo/release-action@v1.6.1
          with:
            bodyFile: "body.md"
            token: ${{ secrets.GITHUB_TOKEN }}